import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";
import GoogleAnalyticsScript from "./GoogleAnalyticsScript";
//import { Inter, Roboto } from "next/font/google";

// const roboto = Roboto({
//   subsets: ["latin"],
//     weight: ["400", "900"],
//   variable: "--font-roboto",
// });


const poppins = localFont({
  src: "../public/fonts/poppins-regular-webfont.woff2",
  variable: "--font-poppins",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <GoogleAnalyticsScript />
        <body className={poppins.variable}>
        <AuthProvider>
        <NavBar />
        <main className="p-5">
          {children}
        </main>
        </AuthProvider>
      </body>
    </html>
  );
}


