// import ProductCard from "./components/ProductCard";
//import Image from "next/image";
// import coffee from "@/public/images/coffee.jpg";

import prisma from "@/prisma/client";
import { Metadata } from "next";

export default async function Home() {

  return (
    <main className="relative h-screen">
      <h1>Hello World</h1>
    </main>
  );
}


export async function generateMetadata(): Promise<Metadata> {

  // fetch data
  const product = await prisma.product.findFirst();
  console.log("META:", product);
  if (!product) {
    return {
      title: "Home",
      description: "Generated by create next app",
    };
  }

  return {
    title: "Home " + product.name,
    description: "Generated by create next app",
  };
}